spring.application.name=springbootoidcclient

server.port=9089
spring.security.oauth2.client.registration.keycloak.client-id=springboot-client
spring.security.oauth2.client.registration.keycloak.client-secret=bNa5PCulEj5MpXkhPDj2frtyItSpTBNN
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/acme
server.max-http-request-header-size=65536
#server.maxHttpHeaderSize=65536
#spring.security.oauth2.client.provider.keycloak.end-session-endpoint=http://localhost:8080/realms/acme/protocol/openid-connect/logout
