#spring.application.name=springbootoidcclient

#server.port=9089
#spring.security.oauth2.client.registration.keycloak.client-id=springboot-client
#spring.security.oauth2.client.registration.keycloak.client-secret=your-client-secret
#spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
#spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/acme
#server.max-http-request-header-size=65536
spring.application.name=springbootoidcclient

server.port=9089
spring.security.oauth2.client.registration.auth0.client-id=your-client-id
spring.security.oauth2.client.registration.auth0.client-secret=your-client-secret
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.auth0.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-jhbg8ojzoqxu3f73.us.auth0.com/