spring.application.name=clienapp

server.port=9089

spring.security.oauth2.client.registration.auth0.client-id=your-client-id
spring.security.oauth2.client.registration.auth0.client-secret=your-client-secret
spring.security.oauth2.client.registration.auth0.scope=openid
spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.auth0.redirect-uri={baseUrl}/login/oauth2/code/{registrationId} 
spring.security.oauth2.client.registration.auth0.client-name=spring-app
spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-n56emmvc0zjkxomk.us.auth0.com/

